
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package AnalizadorPalabras;

import java_cup.runtime.*;
import java.util.ArrayList;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class SintacticoPalabras extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public SintacticoPalabras() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public SintacticoPalabras(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public SintacticoPalabras(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\004\000\002\002\004\000\002\002\004\000\002\003" +
    "\005\000\002\003\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\010\000\004\006\005\001\002\000\006\004\010\005" +
    "\011\001\002\000\006\004\ufffe\005\ufffe\001\002\000\004" +
    "\002\007\001\002\000\004\002\001\001\002\000\004\006" +
    "\012\001\002\000\004\002\000\001\002\000\006\004\uffff" +
    "\005\uffff\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\010\000\006\002\005\003\003\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$SintacticoPalabras$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$SintacticoPalabras$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$SintacticoPalabras$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    ArrayList<String> words = new ArrayList<String>();
    
    public void syntax_error(Symbol s){ 
        System.out.println("Error Sintáctico en la Línea " + (s.left) +
        " Columna "+s.right+ ". No se esperaba este componente: " +s.value+"."); 
    } 

    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{ 
        System.out.println("Error síntactico irrecuperable en la Línea " + 
        (s.left)+ " Columna "+s.right+". Componente " + s.value + 
        " no reconocido."); 
    }  



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$SintacticoPalabras$actions {
  private final SintacticoPalabras parser;

  /** Constructor */
  CUP$SintacticoPalabras$actions(SintacticoPalabras parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$SintacticoPalabras$do_action_part00000000(
    int                        CUP$SintacticoPalabras$act_num,
    java_cup.runtime.lr_parser CUP$SintacticoPalabras$parser,
    java.util.Stack            CUP$SintacticoPalabras$stack,
    int                        CUP$SintacticoPalabras$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$SintacticoPalabras$result;

      /* select the action based on the action number */
      switch (CUP$SintacticoPalabras$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= S EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$SintacticoPalabras$stack.elementAt(CUP$SintacticoPalabras$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$SintacticoPalabras$stack.elementAt(CUP$SintacticoPalabras$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$SintacticoPalabras$stack.elementAt(CUP$SintacticoPalabras$top-1)).value;
		RESULT = start_val;
              CUP$SintacticoPalabras$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$SintacticoPalabras$stack.elementAt(CUP$SintacticoPalabras$top-1)), ((java_cup.runtime.Symbol)CUP$SintacticoPalabras$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$SintacticoPalabras$parser.done_parsing();
          return CUP$SintacticoPalabras$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // S ::= L PUNTO 
            {
              Object RESULT =null;
		  
    System.out.print("> Salida: ");
    for(int i = 1; i < words.size(); i++) {
        System.out.print(words.get(i) + ", ");
    }
    System.out.print(words.get(0) + ".\n");

              CUP$SintacticoPalabras$result = parser.getSymbolFactory().newSymbol("S",0, ((java_cup.runtime.Symbol)CUP$SintacticoPalabras$stack.elementAt(CUP$SintacticoPalabras$top-1)), ((java_cup.runtime.Symbol)CUP$SintacticoPalabras$stack.peek()), RESULT);
            }
          return CUP$SintacticoPalabras$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // L ::= L COMA WORD 
            {
              Object RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$SintacticoPalabras$stack.peek()).left;
		int xright = ((java_cup.runtime.Symbol)CUP$SintacticoPalabras$stack.peek()).right;
		String x = (String)((java_cup.runtime.Symbol) CUP$SintacticoPalabras$stack.peek()).value;
		 words.add(x); 
              CUP$SintacticoPalabras$result = parser.getSymbolFactory().newSymbol("L",1, ((java_cup.runtime.Symbol)CUP$SintacticoPalabras$stack.elementAt(CUP$SintacticoPalabras$top-2)), ((java_cup.runtime.Symbol)CUP$SintacticoPalabras$stack.peek()), RESULT);
            }
          return CUP$SintacticoPalabras$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // L ::= WORD 
            {
              Object RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$SintacticoPalabras$stack.peek()).left;
		int xright = ((java_cup.runtime.Symbol)CUP$SintacticoPalabras$stack.peek()).right;
		String x = (String)((java_cup.runtime.Symbol) CUP$SintacticoPalabras$stack.peek()).value;
		 words.add(x); 
              CUP$SintacticoPalabras$result = parser.getSymbolFactory().newSymbol("L",1, ((java_cup.runtime.Symbol)CUP$SintacticoPalabras$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoPalabras$stack.peek()), RESULT);
            }
          return CUP$SintacticoPalabras$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$SintacticoPalabras$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$SintacticoPalabras$do_action(
    int                        CUP$SintacticoPalabras$act_num,
    java_cup.runtime.lr_parser CUP$SintacticoPalabras$parser,
    java.util.Stack            CUP$SintacticoPalabras$stack,
    int                        CUP$SintacticoPalabras$top)
    throws java.lang.Exception
    {
              return CUP$SintacticoPalabras$do_action_part00000000(
                               CUP$SintacticoPalabras$act_num,
                               CUP$SintacticoPalabras$parser,
                               CUP$SintacticoPalabras$stack,
                               CUP$SintacticoPalabras$top);
    }
}

}
